apis_core/apis_entities/urls.py
from django.urls import path

from . import detail_views, views
from .autocomplete3 import GenericEntitiesAutocomplete
from .list_view_event import EventListView
from .list_view_institution import InstitutionListView
from .list_view_person import PersonListView
from .list_view_place import PlaceListView
from .list_view_work import WorkListView
from .arc_views import get_arcs_data, ArcsView

app_name = "apis_entities"

urlpatterns = [
    path(
        "arcs-data",
        get_arcs_data,
        name="arcs_data",
    ),
    path(
        "arcs",
        ArcsView.as_view(),
        name="arcs",
    ),
    path(
        "entity/<entity>/<int:pk>/edit",
        views.GenericEntitiesEditView.as_view(),
        name="generic_entities_edit_view",
    ),
    path(
        "entity/<entity>/<int:pk>/detail",
        detail_views.GenericEntitiesDetailView.as_view(),
        name="generic_entities_detail_view",
    ),
    path(
        "entity/<entity>/create",
        views.GenericEntitiesCreateView.as_view(),
        name="generic_entities_create_view",
    ),
    path(
        "entity/<entity>/<int:pk>/delete",
        views.GenericEntitiesDeleteView.as_view(),
        name="generic_entities_delete_view",
    ),
    path(
        "entity/person/list/",
        PersonListView.as_view(),
        name="person_list_view",
    ),
    path(
        "entity/place/list/",
        PlaceListView.as_view(),
        name="place_list_view",
    ),
    path(
        "entity/work/list/",
        WorkListView.as_view(),
        name="work_list_view",
    ),
    path(
        "entity/institution/list/",
        InstitutionListView.as_view(),
        name="institution_list_view",
    ),
    path(
        "entity/event/list/",
        EventListView.as_view(),
        name="event_list_view",
    ),
    path(
        "merge/<entity>/<int:ent_merge_pk>/",
        views.MergeEntitiesView.as_view(),
        name="merge_view",
    ),
    path(
        "autocomplete/<entity>/<int:ent_merge_pk>/",
        GenericEntitiesAutocomplete.as_view(),
        name="generic_entities_autocomplete",
    ),
    path(
        "autocomplete/<entity>/",
        GenericEntitiesAutocomplete.as_view(),
        name="generic_entities_autocomplete",
    ),
    path(
        "autocomplete/<entity>/<db_include>/",
        GenericEntitiesAutocomplete.as_view(),
        name="generic_entities_autocomplete",
    ),
]

network/urls.py
from django.urls import path
from network.views import (
    EdgeListViews,
    network_data,
    NetworkView,
    CalenderView,
    edges_as_geojson,
    edges_as_calender,
    MapView,
    get_realtions_as_tei,
)


app_name = "network"
urlpatterns = [
    path("edges/", EdgeListViews.as_view(), name="edges_browse"),
    path("network-data/", network_data, name="data"),
    path("network/", NetworkView.as_view(), name="network"),
    path("geojson-data/", edges_as_geojson, name="geojson"),
    path("calender-data/", edges_as_calender, name="calender_data"),
    path("calender/", CalenderView.as_view(), name="calender"),
    path("map/", MapView.as_view(), name="map"),
    path("tei/", get_realtions_as_tei, name="tei"),
]

pmb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from apis_core.apis_entities import resolver_views
from django.views.generic.base import TemplateView


urlpatterns = [
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("network/", include("network.urls", namespace="network")),
    path("apis/", include("apis_core.urls", namespace="apis")),
    path("normdata/", include("normdata.urls", namespace="normdata")),
    path("admin/", admin.site.urls),
    path("arche/", include("archemd.urls", namespace="archemd")),
    path("uri/", resolver_views.uri_resolver, name="uri-resolver"),
    path("entity/<int:pk>/", resolver_views.entity_resolver, name="entity-resolver"),
    path('tinymce/', include('tinymce.urls')),
    path("", include("dumper.urls", namespace="dumper")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

apis_core/apis_entities/views.py
import importlib

from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.loader import select_template
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DeleteView
from django_tables2 import RequestConfig

from apis_core.apis_entities.models import AbstractEntity, TempEntityClass
from apis_core.apis_labels.models import Label
from apis_core.apis_relations.models import AbstractRelation
from apis_core.apis_relations.tables import LabelTableEdit, get_generic_relations_table

from .forms import MergeForm, get_entities_form


@method_decorator(login_required, name="dispatch")
class GenericEntitiesEditView(View):
    def get(self, request, *args, **kwargs):
        entity = kwargs["entity"]
        pk = kwargs["pk"]
        entity_model = AbstractEntity.get_entity_class_of_name(entity)
        instance = get_object_or_404(entity_model, pk=pk)
        relations = AbstractRelation.get_relation_classes_of_entity_name(
            entity_name=entity
        )
        side_bar = []
        for rel in relations:
            match = [
                rel.get_related_entity_classa().__name__.lower(),
                rel.get_related_entity_classb().__name__.lower(),
            ]
            prefix = "{}{}-".format(match[0].title()[:2], match[1].title()[:2])
            title_card = ""
            if match[0] == match[1]:
                title_card = entity.title()
                dict_1 = {"related_" + entity.lower() + "a": instance}
                dict_2 = {"related_" + entity.lower() + "b": instance}
                objects = rel.objects.filter(Q(**dict_1) | Q(**dict_2))
                link_to_relations = f"{rel.get_listview_url()}?source_target={pk}"
            else:
                link_to_relations = f"{rel.get_listview_url()}?source_target={pk}"
                if match[0].lower() == entity.lower():
                    title_card = match[1].title()
                else:
                    title_card = match[0].title()
                dict_1 = {"related_" + entity.lower(): instance}
                objects = rel.objects.filter(**dict_1)
            object_count = objects.count()
            disable_sort = False
            if object_count > 20:
                if object_count > 20:
                    objects = objects[:20]
                    disable_sort = True
            table = get_generic_relations_table(
                relation_class=rel,
                entity_instance=instance,
                detail=False,
                disable_sort=disable_sort,
            )
            tb_object = table(data=objects, prefix=prefix)
            tb_object_open = request.GET.get(prefix + "page", None)
            RequestConfig(request, paginate={"per_page": 10}).configure(tb_object)
            side_bar.append(
                (
                    title_card,
                    tb_object,
                    "".join([x.title() for x in match]),
                    tb_object_open,
                    link_to_relations,
                    disable_sort,
                    object_count,
                )
            )
        form = get_entities_form(entity.title())
        form = form(instance=instance)
        form_merge_with = MergeForm(entity, ent_merge_pk=pk)
        object_labels = Label.objects.filter(temp_entity=instance)
        tb_label = LabelTableEdit(data=object_labels, prefix=entity.title()[:2] + "L-")
        tb_label_open = request.GET.get("PL-page", None)
        side_bar.append(("Label", tb_label, "PersonLabel", tb_label_open))
        RequestConfig(request, paginate={"per_page": 10}).configure(tb_label)
        template = select_template(
            [
                "apis_entities/edit_view.html",
            ]
        )
        context = {
            "entity_type": entity,
            "form": form,
            "form_merge_with": form_merge_with,
            "instance": instance,
            "right_card": side_bar,
        }
        return HttpResponse(template.render(request=request, context=context))

    def post(self, request, *args, **kwargs):
        entity = kwargs["entity"]
        pk = kwargs["pk"]
        entity_model = AbstractEntity.get_entity_class_of_name(entity)
        instance = get_object_or_404(entity_model, pk=pk)
        form = get_entities_form(entity.title())
        form = form(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(
                reverse(
                    "apis:apis_entities:generic_entities_edit_view",
                    kwargs={"pk": pk, "entity": entity},
                )
            )
        else:
            template = select_template(
                [
                    "apis_entities/{}_create_generic.html".format(entity),
                    "apis_entities/create_view.html",
                ]
            )
            context = {
                "form": form,
                "entity_type": entity,
                "instance": instance,
            }
            if entity.lower() != "place":
                return TemplateResponse(request, template, context=context)
            return HttpResponse(template.render(request=request, context=context))


@method_decorator(login_required, name="dispatch")
class GenericEntitiesCreateView(View):
    def get(self, request, *args, **kwargs):
        entity = kwargs["entity"]
        form = get_entities_form(entity.title())
        form = form()
        template = select_template(
            [
                "apis_entities/{}_create_generic.html".format(entity),
                "apis_entities/create_view.html",
            ]
        )
        return HttpResponse(
            template.render(
                request=request,
                context={
                    "entity_type": entity,
                    "form": form,
                },
            )
        )

    def post(self, request, *args, **kwargs):
        entity = kwargs["entity"]
        form = get_entities_form(entity.title())
        form = form(request.POST)
        if form.is_valid():
            entity_2 = form.save()
            return redirect(
                reverse(
                    "apis:apis_entities:generic_entities_detail_view",
                    kwargs={"pk": entity_2.pk, "entity": entity},
                )
            )
        else:
            permissions = {
                "create": request.user.has_perm("apis_entities.add_{}".format(entity))
            }
            template = select_template(
                [
                    "apis_entities/{}_create_generic.html".format(entity),
                    "apis_entities/create_view.html",
                ]
            )
            return HttpResponse(
                template.render(
                    request=request,
                    context={
                        "permissions": permissions,
                        "form": form,
                    },
                )
            )


@method_decorator(login_required, name="dispatch")
class GenericEntitiesDeleteView(DeleteView):
    model = importlib.import_module("apis_core.apis_metainfo.models").TempEntityClass
    template_name = "apis_entities/confirm_delete.html"

    def dispatch(self, request, *args, **kwargs):
        entity = kwargs["entity"]
        self.success_url = reverse(f"apis_core:apis_entities:{entity}_list_view")
        return super(GenericEntitiesDeleteView, self).dispatch(request, *args, **kwargs)


@method_decorator(login_required, name="dispatch")
class MergeEntitiesView(View):
    def post(self, request, *args, **kwargs):
        entity = kwargs["entity"]
        ent_merge_pk = kwargs.get("ent_merge_pk", False)
        form = MergeForm(entity, request.POST, ent_merge_pk=ent_merge_pk)
        if form.is_valid():
            target_id = form.data["entity"]
            if ent_merge_pk:
                target = TempEntityClass.objects.get(id=target_id)
                entity_model_class = ContentType.objects.get(
                    app_label="apis_entities", model__iexact=entity
                ).model_class()
                target_obj = entity_model_class.objects.get(id=target.id)
                target_obj.merge_with(int(ent_merge_pk))
            return redirect(
                reverse(
                    "apis:apis_entities:generic_entities_detail_view",
                    kwargs={"pk": target.pk, "entity": entity},
                )
            )
        else:
            return redirect(
                reverse(
                    "apis:apis_entities:generic_entities_edit_view",
                    kwargs={"pk": ent_merge_pk, "entity": entity},
                )
            )

apis_core/apis_entities/templates/apis_entities/detail_views/entity_detail_generic.html
{% extends "base.html" %}
{% load static %}
{% load django_tables2 %}
{% block title %} {{ object }} {% endblock %}
{% block content %}
{% include "partials/entity_styles.html" %}

<div class="container-fluid pt-4 ps-4 pe-4">
    
    <div class="row">
        <div class="col-md-2">
            {% if object.get_prev_url %}
                <h2>
                    <a href="{{ object.get_prev_url }}" style="float:right">
                        <i class="bi bi-chevron-left" title="vorige Entität"></i>
                    </a>
                </h2>
            {% endif %}
        </div>
        <div class="col-md-8">
            <h2 class="display-4 text-center">
                <a href="{{ object.get_listview_url }}" title="zurück zur Übersicht">
                    <i class="{{ object.get_icon }}"></i>
                </a>
               {{ object }}
            </h2>
            {% if user.is_authenticated %}
                <h2 class="text-center">
                    {% if object.get_edit_url %}
                            <a href="{{ object.get_edit_url }}">
                                <i class="bi bi-pencil-square" title="Entität bearbeiten"></i>
                            </a>
                    {% endif %}
                    {% if object.get_delete_url %}
                        |
                            <a href="{{ object.get_delete_url }}">
                                <i class="bi bi-trash3" title="Entität löschen"></i>
                            </a>
                    {% endif %}
                </h2>
            {% endif %}
        </div>
        <div class="col-md-2">
            {% if object.get_next_url %}
                <h2>
                    <a href="{{ object.get_next_url }}" style="float:left">
                        <i class="bi bi-chevron-right" title="nächste Entität"></i>
                    </a>
                </h2>
            {% endif %}
        </div>
    </div>
   
    <div class="row p-5">
        <div class="col-md-4">
            <table class="table table-borderless table-hover ps-3 ">
                {% if object.img_url and object.img_credit_label != 'AKON' %}
                <tr>
                    <th class="w-25">&#160;</th>
                    <td>
                        <img src="{{ object.img_url }}" class="rounded" alt="Bild von {{ object }}" style="height: 200px">
                        {% if object.img_credit %}
                        <figcaption class="figure-caption"><a href="{{ object.img_credit }}" style="color: dimgrey;">{{ object.img_credit_label }}</a></figcaption>
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
            {% block info-table %}
                <tr>
                    <th class="w-25">
                        Titel
                    </th>
                    <td>
                        {{ object.name }}
                    </td>
                </tr>
                {% if no_merge_labels %}
                <tr>
                    <th class="w-25">
                        Labels
                    </th>
                    <td>
                        {% for x in no_merge_labels %}
                        <small>{{ x.label_type }}: </small>{{ x.label }}<br >
                        {% endfor %}
                    </td>
                </tr>
                {% endif %}
                <tr>
                    <th class="w-25">
                        ID
                    </th>
                    <td>
                        {{ object.id }}
                    </td>
                </tr>
                <tr>
                    <th class="w-25">
                        Typ
                    </th>
                    <td>
                        {{ object.kind}}
                    </td>
                </tr>
                {% if object.start_date or object.end_date %}
                <tr>
                    <th class="w-25">
                        Datum
                    </th>
                    <td>
                        {% if object.start_date_written %}
                            <abbr title="{{ object.start_date }}">{{ object.start_date_written }}</abbr>
                        {% endif %}
                        {% if object.end_date %}
                            - <abbr title="{{ object.end_date }}">{{ object.end_date_written }}</abbr>
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
            {% endblock info-table %}
            {% block info-metadata %}
                <tr>
                    <th class="w-25">Export</th>
                    <td>
                        <a href="{{ object.get_tei_url }}" title="zur TEI-Ansicht der Entität">
                            <i class="bi bi-filetype-xml"></i> TEI
                        </a>
                        |
                        <a href="{{ object.get_api_url }}">
                            <i class="bi bi-database" title="zur API-Ansicht der Entität"></i> JSON
                        </a> 
                    </td>
                </tr>
                <tr>
                    <th class="w-25">
                        PMB-URI
                    </th>
                    <td>
                        <a href="https://pmb.acdh.oeaw.ac.at/entity/{{ object.id }}/">https://pmb.acdh.oeaw.ac.at/entity/{{ object.id }}/</a>
                    </td>
                </tr>
                <tr>
                    <th class="w-25">
                        Verknüpfte Datensätze
                    </th>
                    <td>
                        {% for x in object.uri_set.all %}
                            {% if user.is_authenticated %}
                        
                                <a href="{{ x }}" style="color:{{ x.get_color }}">{{ x }}</a> {% if user.is_authenticated %} <a href="{{ x.get_edit_url }}" title="URI bearbeiten">
                                    <i class="bi bi-pencil-square"></i>
                                </a> | <a href="{{ x.get_delete_url }}" title="URI löschen">
                                    <i class="bi bi-trash3"></i>
                                </a>{% endif %}<br />
                            {% else %}
                            {% if x.domain != "pmb" %}
                            <a class="m2 fs-5" href="{{ x }}" style="color:{{ x.get_color }}"><span class="badge" style="background-color:{{ x.get_color }}">{{ x.domain }}</span></a>
                            {% endif %}
                            {% endif %}
                        {% endfor %}
                    </td>
                </tr>
                    {% if object.collection.all %}
                    <tr>
                        <th class="left-width">
                            Sammlungen
                        </th>
                        <td>
                            {% for x in object.collection.all %}
                            {% if "Wikipedia" in x.name %}
                            {% else %}
                            {{ x }}<br />
                            {% endif %}
                            {% endfor %}
                            
                        </td>
                    </tr>
                    {% endif %}
                    {% if object.notes %}
                        <tr>
                            <th class="w-25">
                                Anmerkungen
                            </th>
                            <td>
                                {{ object.notes }}
                            </td>
                        </tr>
                    {% endif %}
                    {% if object.references %}
                        <tr>
                            <th class="w-25">
                                Belege
                            </th>
                            <td>
                                {{ object.references }}
                            </td>
                        </tr>
                    {% endif %}
                </table>
            {% endblock info-metadata %}
            {% block left-pane-additional %}
            {% endblock left-pane-additional %}
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-7">
            <h3 class="text-center mt-5">
                Beziehungen
                <a href="{% url 'network:edges_browse' %}?node_id={{ object.id }}" title="Alle Relationen von {{ object }}"><i class="ps-2 bi bi-box-arrow-up-right" aria-hidden="true"><span class="visually-hidden">Alle Relationen von {{ object }}</span></i></a>
                <a href="{% url 'network:network' %}?node_id={{ object.id }}&format=cosmograph" title="Alle Relationen von {{ object }} als Netzwerk"><i class="ps-2 bi bi-share" aria-hidden="true"><span class="visually-hidden">Alle Relationen von {{ object }} als Netzwerk</span></i></a>
            </h3>
            {% block relations %}
                {% for obj in right_card %}
                    {% if obj.1.data|length > 0 %}
                        <h4>{{ obj.0 }} {% if obj.5 %}<a class="apis-{{ obj.5 }}" title="Gehe zu {{ object }}–{{ obj.0 }} Relationen" href="{{ obj.4 }}"><i class="bi bi-box-arrow-up-right" aria-hidden="true"><span class="visually-hidden">Gehe zu {{ object }} - {{ obj.5 }} Relationen</span></i></a> {% if obj.6 %} <span class="fs-6 fw-light">An dieser Stelle werden nur maximal 10 Beziehungen angezeigt. Alle Beziehungen <a title="Gehe zu {{ object }}–{{ obj.0 }} Relationen" href="{{ obj.4 }}"><strong>hier</strong></a></span> {% endif %}{% endif %}</h4>
                   
                        <div id="tab_{{ obj.2 }}" class="mb-5">
                            {% render_table obj.1 %}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endblock relations %}
        </div>
    </div>
</div>
{% endblock content %}

apis_core/apis_entities/templates/apis_entities/detail_views/person_detail.html
{% extends "apis_entities/detail_views/entity_detail_generic.html" %}

    {% block info-table %}
        <tr>
            <th class="w-25">
                Name
            </th>
            <td>
                {{ object }}
            </td>
        </tr>
        {% if no_merge_labels %}
        <tr>
            <th class="w-25">
                anderer Name
            </th>
            <td>
                {% for x in no_merge_labels %}
                    <li class="list-unstyled">
                        <small>{{ x.label_type }}: </small>{{ x.label }}
                    </li>
                {% endfor %}
                
            </td>
        </tr>
        {% endif %}
        <tr>
            <th class="w-25">
                ID
            </th>
            <td>
                {{ object.id }}
            </td>
        </tr>
        <tr>
          <th class="w-25">
            Gender
          </th>
          <td>
            {{ object.gender }}
          </td>
        </tr>
        {% if object.start_date or object.end_date %}
        <tr>
            <th class="w-25">
                Zeit
            </th>
            <td>
                {% if object.start_date %}
                    <abbr title="{{ object.start_date }}">{{ object.start_date_written }}</abbr>
                {% endif %}
                {% if object.end_date %}
                    - <abbr title="{{ object.end_date }}">{{ object.end_date_written }}</abbr>
                {% endif %}
            </td>
        </tr>
        {% endif %}
        {% if object.profession.all %}
        <tr>
            <th class="w-25">
                Berufe
            </th>
            <td>
              {% for prof in object.profession.all %}
                {{ prof.name }}{% if forloop.last %}{% else %},{% endif %}
              {% endfor %}
            </td>
        </tr>
        {% endif %}
    {% endblock info-table %}

apis_core/apis_entities/templates/apis_entities/detail_views/person_detail_generic.html
{% extends "apis_entities/detail_views/entity_detail_generic.html" %}

    {% block info-table %}
    <table class="table">
        <tr>
            <th>
                Name
            </th>
            <td>
                {{ object.name }}, {{ object.first_name }}
            </td>
        </tr>
        {% if no_merge_labels %}
        <tr>
            <th>
                Alternative Namen
            </th>
            <td>
                {% for x in no_merge_labels %}
                    <li class="list-unstyled">
                        <small>{{ x.label_type }}: </small>{{ x.label }}
                    </li>
                {% endfor %}
                
            </td>
        </tr>
        {% endif %}
        <tr>
            <th>
                ID
            </th>
            <td>
                {{ object.id }}
            </td>
        </tr>
        <tr>
          <th>
            Gender
          </th>
          <td>
            {{ object.gender }}
          </td>
        </tr>
        {% if object.start_date or object.end_date %}
        <tr>
            <th>
                Lifespan
            </th>
            <td>
                {% if object.start_date %}
                    <abbr title="{{ object.start_date }}">{{ object.start_date_written }}</abbr>
                {% endif %}
                {% if object.end_date %}
                    - <abbr title="{{ object.end_date }}">{{ object.end_date_written }}</abbr>
                {% endif %}
            </td>
        </tr>
        {% endif %}
        {% if object.profession.all %}
        <tr>
            <th>
                Professions
            </th>
            <td>
              {% for prof in object.profession.all %}
                {{ prof.name }}{% if forloop.last %}{% else %},{% endif %}
              {% endfor %}
            </td>
        </tr>
        {% endif %}
    </table>
    {% endblock info-table %}

apis_core/apis_entities/templates/apis_entities/detail_views/place_detail.html
{% extends "apis_entities/detail_views/entity_detail_generic.html" %}

    {% block info-table %}
    {% if object.lat %}
    {% include "partials/leaflet.html" %}
        <div id="map" style="height: 300px;"></div>
        <script>
            var lat = "{{ object.lat }}".replace(",", "."); 
            var lng = "{{ object.lng }}".replace(",", "."); 
            var map = L.map('map').setView([lat, lng], 13);
            L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
                maxZoom: 19,
                attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
            }).addTo(map);
            var marker = L.marker([lat, lng]).addTo(map);
            marker.bindPopup("{{ object.name }}").openPopup();
        </script>
    {% endif %}

        {% if no_merge_labels %}
        <tr>
            <th class="w-25">
                Alternative Namen
            </th>
            <td>
                {% for x in no_merge_labels %}
                    <li class="list-unstyled">
                        <small>{{ x.label_type }}: </small>{{ x.label }}
                    </li>
                {% endfor %}
                
            </td>
        </tr>
        {% endif %}
        <tr>
            <th class="w-25">
                ID
            </th>
            <td>
                {{ object.id }}
            </td>
        </tr>
        <tr>
            <th class="w-25">
                Koordinaten
            </th>
            <td>
                {{ object.lat }} {{ object.lng}}
            </td>
        </tr>
        <tr>
            <th class="w-25">Ortstype</th>
            <td>{% if object.kind.description %} {{ object.kind }} <small>{{ object.kind.description }}</small> {% else %} {{ object.kind }} {% endif %}</td>
        </tr>
        {% if object.start_date_written or object.end_date_written %}
        <tr>
            <th class="w-25">von – bis</th>
            <td>{% if object.start_date_written %}{{ object.start_date_written }}{% endif %}{% if object.end_date_written %} – {{ object.end_date_written }}{% endif %}</td>
        </tr>
        {% endif %}
    
    {% endblock info-table %}