dumper/urls.py
from django.urls import path

from dumper import views

app_name = "dumper"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("export/", views.ExportView.as_view(), name="export"),
    path("imprint/", views.ImprintView.as_view(), name="imprint"),
    path("login/", views.user_login, name="user_login"),
    path("logout/", views.user_logout, name="user_logout"),
]

network/urls.py
from django.urls import path
from network.views import (
    EdgeListViews,
    network_data,
    NetworkView,
    CalenderView,
    edges_as_geojson,
    edges_as_calender,
    MapView,
    get_realtions_as_tei,
)


app_name = "network"
urlpatterns = [
    path("edges/", EdgeListViews.as_view(), name="edges_browse"),
    path("network-data/", network_data, name="data"),
    path("network/", NetworkView.as_view(), name="network"),
    path("geojson-data/", edges_as_geojson, name="geojson"),
    path("calender-data/", edges_as_calender, name="calender_data"),
    path("calender/", CalenderView.as_view(), name="calender"),
    path("map/", MapView.as_view(), name="map"),
    path("tei/", get_realtions_as_tei, name="tei"),
]

normdata/urls.py
from django.urls import path

from . import views

app_name = "normdata"


urlpatterns = [
    path(
        "import-from-normdata/",
        views.NormDataImportFormView.as_view(),
        name="import_from_normdata",
    )
]

pmb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from apis_core.apis_entities import resolver_views
from django.views.generic.base import TemplateView


urlpatterns = [
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("network/", include("network.urls", namespace="network")),
    path("apis/", include("apis_core.urls", namespace="apis")),
    path("normdata/", include("normdata.urls", namespace="normdata")),
    path("admin/", admin.site.urls),
    path("arche/", include("archemd.urls", namespace="archemd")),
    path("uri/", resolver_views.uri_resolver, name="uri-resolver"),
    path("entity/<int:pk>/", resolver_views.entity_resolver, name="entity-resolver"),
    path('tinymce/', include('tinymce.urls')),
    path("", include("dumper.urls", namespace="dumper")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

templates/partials/entity_styles.html
{% if entity_type %}
<style>
    a {
        color: var(--{{ entity_type }});
    }
    .navbar {
        border-bottom: 5px solid var(--pmb);
    }
    #searchpane {
        border-right: 1px solid var(--{{ entity_type }});
    }

    h1, h2 {
        color: var(--{{ entity_type }});
    }
    tr.htmx-swapping td {
        opacity: 0;
        transition: opacity 1s ease-out;
      }
</style>
{% else %}
<style>
    a {
        color: var(--{{ entity }});
    }
    .navbar {
        border-bottom: 5px solid var(--{{ pmb }});
    }
    #searchpane {
        border-right: 1px solid var(--{{ entity }});
    }

    h1, h2 {
        color: var(--{{ entity }});
    }
    tr.htmx-swapping td {
        opacity: 0;
        transition: opacity 1s ease-out;
      }
</style>
{% endif %}

templates/partials/footer.html
{% load static %}
<footer class="footer mt-auto py-3 bg-body-tertiary">
    <div class="container" tabindex="-1">
        <div class="footer-separator">
            KONTAKT
        </div>
        <div class="row justify-content-between">
            <div class="col-lg-1 col-md-2 col-sm-2 col-xs-6 col-3">
                <a href="/">
                    <img src="{% static 'img/acdh_logo.svg' %}" class="image" alt="ACDH Logo" style="max-width: 100%; height: auto;" title="ACDH Logo"/>
                </a>
            </div>
            <!-- .-->
            <div class="col-lg-4 col-md-4 col-sm-6 col-9">
                <p>
                    ACDH
                    <br/>
                    Austrian Centre for Digital Humanities
                    <br/>
                    Österreichische Akademie der Wissenschaften
                </p>
                <p>
                    Bäckerstraße 13
                    <br/>
                    1010 Wien
                </p>
                <p>
                    T: +43 1 51581-2200
                    <br/>
                    E: <a
                        href="mailto:acdh-helpdesk@oeaw.ac.at"
                        >acdh-helpdesk(at)oeaw.ac.at</a>
                </p>
            </div>
            <!-- .footer-widget -->
            <div class="footer-widget col-lg-3 col-md-4 col-sm-4 ml-auto">
                <div class="textwidget custom-html-widget">
                    <span class="fs-6 fw-bold">Work in Progress</span><br />
                    <span class="fs-6 fw-bold">Lizenz der Inhalte: <a href="https://creativecommons.org/licenses/by/4.0/deed.en">CC BY 4.0</a></span>
                    <p>Bei Fragen, Anmerkungen, Kritik, aber gerne auch Lob, wenden Sie sich bitte an den <a href="mailto:acdh-helpdesk@oeaw.ac.at" class="footerlink">ACDH Helpdesk</a>
                    </p>
                    <p>
                        <a class="helpdesk-button" class="footerlink"
                            href="mailto:acdh-helpdesk@oeaw.ac.at">e-Mail</a>
                    </p>
                </div>
                <div class="textwidget custom-html-widget">
                    <a href="https://github.com/arthur-schnitzler/pmb-service">
                        <i class="bi bi-github fs-2" class="footerlink" aria-hidden="true"></i>
                        <span class="visually-hidden">GitHub repo</span>
                    </a>
                </div>
            </div>
            <!-- .footer-widget -->
        </div>
    </div>
<div class="footer-imprint-bar hide-reading" id="wrapper-footer-secondary"
    style="text-align:center; padding:0.4rem 0; font-size: 0.9rem;"> © Copyright OEAW | <a
        href="{% url 'dumper:imprint' %}">Impressum</a>
</div>
</footer>

templates/partials/head.html
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
{% block metaDescription %}
{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
  integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
  crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'img/site.webmanifest' %}">
<link rel="mask-icon" href="{% static 'img/safari-pinned-tab.svg' %}" color="#5bbad5">
<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="{% static 'img/browserconfig.xml' %}">
<meta name="theme-color" content="#ffffff">

<script type="text/javascript">
  var _paq = _paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function () {
    var u = "https://matomo.acdh.oeaw.ac.at/";
    _paq.push(['setTrackerUrl', u + 'piwik.php']);
    _paq.push(['setSiteId', '124']);
    var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
    g.type = 'text/javascript'; g.async = true; g.defer = true; g.src = u + 'piwik.js'; s.parentNode.insertBefore(g, s);
  })();</script>
{% block scriptHeader %}
{% endblock scriptHeader %}

templates/partials/leaflet.html
{% load static %}
<link rel="stylesheet" href="{% static 'leaflet/dist/leaflet.css' %}" />
<script src="{% static 'leaflet/dist/leaflet.js' %}"></script>

templates/partials/leaflet_heatmap.html
{% load static %}
<script src="{% static 'Leaflet.heat-0.2.0/dist/leaflet-heat.js' %}"></script>

templates/partials/leaflet_markercluster.html
{% load static %}
<link rel="stylesheet" href="{% static 'leaflet/dist/leaflet.css' %}" />
<link rel="stylesheet" href="{% static 'Leaflet.markercluster-1.4.1/dist/MarkerCluster.Default.css' %}" />
<link rel="stylesheet" href="{% static 'Leaflet.markercluster-1.4.1/dist/MarkerCluster.css' %}" />
<script src="{% static 'leaflet/dist/leaflet.js' %}"></script>
<script src="{% static 'Leaflet.markercluster-1.4.1/dist/leaflet.markercluster.js' %}"></script>

templates/partials/navbar.html
{% load static %}
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'dumper:home' %}">
                <img src="{% static 'img/project-logo.svg' %}" alt="PMB-Logo" />
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Info
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'dumper:about' %}">Über das Projekt</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'apis:apis_metainfo:collection_browse' %}">Datengeber</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'dumper:export' %}">Datenexport</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Entitäten
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'apis:apis_entities:person_list_view' %}">
                                    <i class="bi bi-people apis-person"></i>
                                    Personen
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'apis:apis_entities:place_list_view' %}">
                                    <i class="bi bi-map apis-place"></i>
                                    Orte
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'apis:apis_entities:work_list_view' %}">
                                    <i class="bi bi-book apis-work"></i>
                                    Werke
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'apis:apis_entities:event_list_view' %}">
                                    <i class="bi bi-calendar3 apis-event"></i>
                                    Ereignisse
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'apis:apis_entities:institution_list_view' %}">
                                    <i class="bi bi-building-gear apis-institution"></i>
                                    Institutionen
                                </a>
                            </li>
                            <li><hr class="dropdown-divider"></li>
                            <li>
                                <a class="dropdown-item" href="{% url 'apis:apis_metainfo:uri_browse' %}">
                                    <i class="bi bi-link-45deg apis-uri"></i>URIs
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Relationen
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li class="text-center">
                                <a class="dropdown-item" href="{% url 'network:edges_browse' %}">
                                    <i class="bi bi-share"></i>
                                    Alle Relationen <i class="bi bi-share"></i>
                                </a>
                            </li>
                            <li><hr class="dropdown-divider"></li>
                            <li>
                                <a class="dropdown-item" href="{% url 'apis:apis_relations:personperson' %}">
                                    <i class="bi bi-people apis-person"></i>
                                    Personen und <i class="bi bi-people apis-person"></i> Personen
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'apis:apis_relations:personplace' %}">
                                    <i class="bi bi-people apis-person"></i>
                                    Personen und <i class="bi bi-map apis-place"></i> Orte
                                    
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'apis:apis_relations:personwork' %}">
                                    <i class="bi bi-people apis-person"></i>
                                    Personen und <i class="bi bi-book apis-work"></i> Werke
                                    
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'apis:apis_relations:personevent' %}">
                                    <i class="bi bi-people apis-person"></i>
                                    Personen und <i class="bi bi-calendar3 apis-event"></i> Ereignisse
                                </a>
                            </li>
                            
                            <li>
                                <a class="dropdown-item" href="{% url 'apis:apis_relations:personinstitution' %}">
                                    <i class="bi bi-people apis-person"></i>
                                    Personen und <i class="bi bi-building-gear apis-institution"></i> Institutionen
                                    
                                </a>
                            </li>
                            <li><hr class="dropdown-divider"></li>
                            <a class="dropdown-item" href="{% url 'apis:apis_relations:institutioninstitution' %}">
                                <i class="bi bi-building-gear apis-institution"></i>
                                Institutionen und <i class="bi bi-building-gear apis-institution"></i>
                                Institutionen
                            </a>
                            <a class="dropdown-item" href="{% url 'apis:apis_relations:institutionplace' %}">
                                <i class="bi bi-building-gear apis-institution"></i>
                                Institutionen und <i class="bi bi-building-gear apis-place"></i> Orte
                            </a>
                            <a class="dropdown-item" href="{% url 'apis:apis_relations:institutionwork' %}">
                                <i class="bi bi-building-gear apis-institution"></i>
                                Institutionen und <i class="bi bi-book apis-work"></i> Werke
                                
                            </a>
                            <a class="dropdown-item" href="{% url 'apis:apis_relations:institutionevent' %}">
                                <i class="bi bi-building-gear apis-institution"></i>
                                Institutionen und <i class="bi bi-building-gear apis-event"></i> Ereignisse
                            </a>
                            <li><hr class="dropdown-divider"></li>
                            <li>
                                <a class="dropdown-item" href="{% url 'apis:apis_relations:placeplace' %}">
                                    <i class="bi bi-map apis-place"></i>
                                    Orte und <i class="bi bi-map apis-place"></i> Orte
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'apis:apis_relations:placework' %}">
                                    <i class="bi bi-map apis-place"></i>
                                    Orte und <i class="bi bi-book apis-work"></i> Werke
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'apis:apis_relations:placeevent' %}">
                                    <i class="bi bi-map apis-place"></i>
                                    Orte und <i class="bi bi-calendar3 apis-event"></i> Ereignisse
                                </a>
                            </li>
                            <li><hr class="dropdown-divider"></li>
                            <a class="dropdown-item" href="{% url 'apis:apis_relations:eventevent' %}">
                                <i class="bi bi-map apis-event"></i>
                                Ereignisse und <i class="bi bi-calendar3 apis-event"></i> Ereignisse
                            </a>
                            <a class="dropdown-item" href="{% url 'apis:apis_relations:eventwork' %}">
                                <i class="bi bi-map apis-event"></i>
                                Ereignisse und <i class="bi bi-book apis-work"></i> Werke
                            </a>
                            <li><hr class="dropdown-divider"></li>
                            <a class="dropdown-item" href="{% url 'apis:apis_relations:workwork' %}">
                                <i class="bi bi-book apis-work"></i>
                                Werke und <i class="bi bi-book apis-work"></i> Werke
                                
                            </a>
                        </ul>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'normdata:import_from_normdata' %}">Import</a>
                    </li>
                    {% endif %}
              
                </ul>
                {% if user.is_authenticated %}
                <a href="{% url 'dumper:user_logout' %}">
                    <i class="bi bi-person-check fs-2 pe-3"></i>
                    <span class="visually-hidden">log out</span>
                </a>
                {% else %}
                <a href="{% url 'dumper:user_login' %}">
                    <i class="bi bi-box-arrow-in-right fs-2 pe-3"></i>
                    <span class="visually-hidden">log in</span>
                </a>
                {% endif %}
            </div>
        </div>
    </nav>
</header>